services:
  windows:
    image: dockurr/windows
    container_name: omarchy-windows
    environment:
      VERSION: "iot10"
      RAM_SIZE: "6G"
      CPU_CORES: "8"
      DISK_SIZE: "64G"
      USERNAME: ""
      PASSWORD: ""
      TZ: "Asia/Kolkata"
      ARGUMENTS: "-rtc base=localtime,clock=host,driftfix=slew -device usb-host,vendorid=0x340e,productid=0x8002"
    privileged: true
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/bus/usb/001/004
    cap_add:
      - NET_ADMIN
    ports:
      - 127.0.0.1:8006:8006
      - 127.0.0.1:3389:3389/tcp
      - 127.0.0.1:3389:3389/udp
    volumes:
      - ${HOME}/.windows:/storage
      - ${HOME}/Windows:/shared
    restart: unless-stopped
    stop_grace_period: 2m
