### Read more at config document: https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md
timeout: 3
default_entry: 2
interface_branding: Omarchy Bootloader
interface_branding_color: 89b4fa
interface_help_color: 89b4fa
interface_help_hidden: yes
interface_help_color_bright: 89b4fa
hash_mismatch_panic: no
wallpaper: boot():/wallpaper.png

term_background: ff11111b
term_margin_gradient: 0
backdrop: 11111b

# Terminal colors (Catppuccin Mocha palette)
term_palette: 11111b;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_palette_bright: 585b70;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4

# Text colors
term_foreground: cdd6f4
term_foreground_bright: cdd6f4
term_background_bright: 585b70
