monitor.alsa.rules = [
  {
    matches = [
      {
        node.nick = "24G4"
        alsa.name = "24G4"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
]
