monitor.alsa.rules = [
  {
    matches = [
      {
        node.nick = "HyperX Virtual Surround Sound"
        alsa.name = "USB Audio"
      }
    ]
    actions = {
      update-props = {
        node.nick = "HyperX Cloud II"
        device.icon-name = "audio-headphones"
        device.form-factor = "headset"
      }
    }
  }
]
