monitor.bluez.rules = [
  {
    matches = [
      {
        api.bluez5.address = "60:55:56:0C:AA:A4"
      }
    ]
    actions = {
      update-props = {
        device.icon-name = "audio-headphones-bluetooth"
        device.form-factor = "headphone"
      }
    }
  }
]
