#!/bin/bash

# This hook is called with the snake-cased name of the theme that has just been set.
# To put it into use, remove .sample from the name.

# Example: Show the name of the theme that was just set.
# notify-send "New theme" "Your new theme is $1"

# Override brave colors.json policy
echo "{}" > "/etc/brave/policies/managed/color.json"

# Append custom css to walker and mako
~/.local/bin/theme-set-walker
~/.local/bin/theme-set-mako
