# Extra autostart processes
# exec-once = uwsm-app -- my-service

exec-once = sh -c '~/.local/bin/omarchy-custom-theme-bg-set "$(cat ~/.cache/omarchy-custom/background.file)"'
exec-once = sleep 10 && notify-send -u critical -t 0 -a "Hardware Reminder" "Cooling Stand" "Did you turn on the cooling stand?"
exec-once = uwsm-app -- ~/.local/bin/hyprland-monitor-refresh

