source = ~/.config/omarchy/current/theme/hyprlock.conf
source = ~/.config/hypr/hyprlock-background-active.conf

$outer_color = rgba(175, 186, 222, 0.3)

## General configs
general {
    ignore_empty_input = true
    hide_cursor = true
}

auth {
    fingerprint:enabled = false
}

animations {
    enabled = false
}

## Password field
input-field {
    monitor =
    size = 440, 50
    position = 0, 0
    halign = center
    valign = center

    inner_color = $color
    outer_color = $outer_color
    outline_thickness = 2
    dots_size = 0.24
    dots_spacing = 0.24

    font_family = JetBrainsMono Nerd Font
    font_color = $font_color

    placeholder_text = Enter Password
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 4
    shadow_passes = 0
    fade_on_empty = false
}

## Full-Screen Dark Overlay
shape {
    monitor =
    size = 100%, 100%
    position = 0, 0
    halign = center
    valign = center
    color = rgba(17, 17, 27, 0.9)
    zindex = -1
}

## Top bar
shape {
    size = 100%, 30
    position = 0, 0
    halign = center
    valign = top
    color = $color
}

## Clock
label {
    text = $TIME
    font_size = 12
    halign = center
    valign = top
    position = 5, -3
    font_family = JetBrainsMono Nerd Font
    color = $font_color
}

## Right portion of top bar
label {
    text = cmd[update:2000] ~/.local/bin/hyprlock-bar-right
    font_size = 12
    text_align = right
    halign = right
    valign = top
    position = -32, -3
    font_family = JetBrainsMono Nerd Font
    color = $font_color
}

## System info line
label {
    text = cmd[update:3600000] ~/.local/bin/hyprlock-system-info
    font_size = 12
    halign = center
    valign = bottom
    position = 0, 100
    font_family = JetBrainsMono Nerd Font
    color = $font_color
}

## Bindings
label {
    text = <span weight="bold">[Super+Esc]</span> <span alpha="86%">Display off</span>   <span weight="bold">[Super+S]</span> <span alpha="86%">Suspend</span>   <span weight="bold">[Super+R]</span> <span alpha="86%">Reboot</span>   <span weight="bold">[Super+P]</span> <span alpha="86%">Power off</span>
    font_size = 12
    halign = center
    valign = bottom
    position = 0, 140
    font_family = JetBrainsMono Nerd Font
    color = $font_color
}
